[toolchain]
package_manager = "bun"

[features]
resolution = true
skip-lint = false

[programs.devnet]
stake_program = "C8f5r1DTWDbhCA8Ci6TNdQJBAZg4SuBCkXP49r9BE8i5"

[programs.localnet]
stake_program = "GtgbhnDFLdbh1kBu4htmBbZrB3c5C8MP8px8Yq5jbstX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
create-test-mints = "bun run migrations/create-test-mints.ts"
deploy-and-initialize = "bun run migrations/deploy-and-initialize.ts"
devnet-deploy = "bun run migrations/devnet-deploy.ts"
test = "bunx ts-mocha -p ./tsconfig.json -t 1000000 \"tests/${TEST_PATTERN:-**/*.ts}\""
update-authority = "bun run migrations/update-authority.ts"

[hooks]
